language: python
sudo: false
os:
    - linux

python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
    - pip install -U pip setuptools wheel
    - pip install -r requirements.txt
    - pip install .
# command to run tests
# script: nosetests -v test.py
script: True
